name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Tesseract 5
      run: |
        sudo add-apt-repository ppa:alex-p/tesseract-ocr-devel -y
        sudo apt install -y tesseract-ocr libtesseract-dev
    - name: Install Rust Nightly
      run: |
        rustup toolchain install nightly
        rustup default nightly
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
